### ISSUE TITLE
Smilei with Lustre filesystem

### ISSUE THREAD

**Issue by ceiag** [SmileiPIC/Smilei#342] opened 2020-12-02 11:12 UTC
We don't have file locking enabled on our lustre filesystem, when submitting a job I receive the following error 

```
This requires fcntl(2) to be implemented. As of 8/25/2011 it is not. Generic MPICH Message: File locking failed in ADIOI_Set_lock(fd 12,cmd F_SETLKW/7,type F_WRLCK/1,whence 0) with return value FFFFFFFF and errno 26.
- If the file system is NFS, you need to use NFS version 3, ensure that the lockd daemon is running on all the machines, and mount the directory with the 'noac' option (no attribute caching).
- If the file system is LUSTRE, ensure that the directory is mounted with the 'flock' option.
ADIOI_Set_lock:: Function not implemented
ADIOI_Set_lock:offset 7600, length 2560
```

I attribute this to hdf5 (1.10.5) trying to the do the MPI I/O. Does Smilei have and option to build without MPI I/O support - I did try compiling the app with serial hdf5 i.e., non-MPI hdf5 but during compilation raised the following error  "HDF5 was not built with --enable-parallel option".

Any advice would be greatly appreciated. 

Many Thanks

Chris

**Comment by mccoys** [comment] 2020-12-02 11:49
Smilei does require parallel Hdf5. 

I am not an expert in filesystem issues, but could this be related to your mpi library? It looks like the error dates from 2011. Maybe a more recent version might help. We don't really use mpich, so we have little experience with it. Instead we have successfully built smilei on many machines using intelmpi or openmpi

**Comment by ceiag** [comment] 2020-12-02 14:26
Thanks for the reply.
I don't believe it is down to the mpi library as the one used is relatively recent. The installation was built with the following,

openmpi 4.0.1
intel 18.0.3 compiler 
hdf5 1.10.5 with mpi enabled.
ucx 1.6.1

**Comment by mccoys** [comment] 2020-12-02 14:33
Here is some info from HDF5 doc. It suggest rebuilding your MPI library. I am not very confident in changing the code itself as I am not sure about the overall consequences on other machines.

https://support.hdfgroup.org/HDF5/faq/parallel.html

> ## What if Parallel HDF5 tests fail with a ROMIO error: File locking failed in ADIOI_Set_lock ... ?
> 
> This means that ROMIO, the MPI-I/O implementation used in mpich and openmpi and many other implementations, is attempting to use file locking when it is not supported by your file system. To resolve that, first you should attempt to rebuild your MPI library to disable file locking. This is the best way to resolve this error for your HDF5 application or any MPI-I/O application on your file system.
> 
> If that is not possible, there is a manual way to do this within your program. Unfortunately, this will require updating your programs and also updating the internal parallel HDF5 tests if you want them to succeed. The following steps are required:
> * In your application code set "romio_ds_read" to "disable" and "romio_ds_write" to "disable" as hints in an MPI_Info object.
> * Use this MPI_Info object to set the info parameter in every call to H5Pset_fapl_mpio(). Most likely this parameter was set to MPI_INFO_NULL.

**Comment by ceiag** [comment] 2020-12-02 17:02
Thanks again. I think I may have a found a workaround. If I execute smilei with the following option it allows the job to run

```
mpirun --mca io ompio -n 2 smilei /path/to/some/file.py
```
My understanding is that `-mca io ompio` is telling the job to use the openmpi parallel/MPI backend i.e, OMPI I/O backend and not the one used by hdf5. Thanks again

**Comment by mccoys** [comment] 2020-12-02 17:17
Thank you for the solution. It could be useful for others. Let me close the issue, but feel free to reopen if it turns out the problem is not really solved.

**Closed by mccoys** 2020-12-02 17:17 UTC
Labels: installation
