### ISSUE TITLE
Prescribed field (electric) does unexpected thing

### ISSUE THREAD

**Issue by phi-kafka** [SmileiPIC/Smilei#298] opened 2020-09-16 15:16 UTC
Dear Smilei developers,
I try to work with "PrescribedField". I found the issues on this topic and use the new branch: 
Version : v4.4-710-g423acdef-prescribed_fields

Here is the description of the problem:
In 2D I put plasma into the simulation box, and try to apply an external electric field. I expect to see the charge separation and a capacitor-like structure. It is like that only for a short time, then everything starts to heat exponentially. I simplified the problem to the minimum and see that the module "PrescribedField" cause the heating even with applied field = 0.0. When this module is commented, system is stable.
1. Prescribed Ex field = 0:
_____________________________
```
#SETTING EXTERNAL FIELD:
PrescribedField(
    field = "Ex",
    profile = 0.0#Profile_Ex
)
```
_____________________________
Energy balance:
![Prescribed_E_0___Energy_evolution____test-debug](https://user-images.githubusercontent.com/4519711/93356398-cafa7700-f847-11ea-81d3-3a0724eefea2.png)

Phase space electrons:
![Prescribed_E_0___eon__x_px__100080____test-debug](https://user-images.githubusercontent.com/4519711/93355793-1eb89080-f847-11ea-9589-bfa24b02377d.png)

Electric field Ex and charge density: 
![Prescribed_E_0___exi_rho_00220____test-debug](https://user-images.githubusercontent.com/4519711/93356258-a1415000-f847-11ea-9f56-3ac76c860fa1.png)

2. No module "PrescribedField":
______________________________
```
#SETTING EXTERNAL FIELD:
#PrescribedField(
#field = "Ex",
#profile = Profile_Ex
#)
```
______________________________
Energy balance:
![Prescribed_E_0___Energy_evolution____test-debug](https://user-images.githubusercontent.com/4519711/93356371-c2a23c00-f847-11ea-9852-fed03ef31d65.png)

Phase space electrons:
![Prescribed_E_0___eon__x_px__100080____test-debug](https://user-images.githubusercontent.com/4519711/93356146-8078fa80-f847-11ea-8960-723916e10f6b.png)

Electric field Ex and charge density:
![Prescribed_E_0___exi_rho_00220____test-debug](https://user-images.githubusercontent.com/4519711/93356338-bb7b2e00-f847-11ea-9715-b75c46b4c11f.png)

________________________________________________________________________________________
I think it is a bug. 
I don't know how it is realized in the code, but I did it in another PIC code, and what I did is adding applied fields to the real field before particle pusher and extract just after. It was working.

Thanks!

ps. I attach the namelist below.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```
import math
import numpy as np

def sintheta(x,d): # 1 for x>0, 0 for x<0;  starts from x=0
    d=d/np.pi
    if x<=0: f=0.
    if x>=np.pi*d : f=1.
    if 0.<x<np.pi*d: f=0.5*(1-np.cos(x/d))
    return f   


#############################################
n0  = 0.000001
Z   = 1.
M    = 100000 # ions
Te  = 0.001
#simulation box
nppc = 4
res  = 16.0
dx   = 1./res
dy   = dx
dt   = 0.9 * dx/math.sqrt(2.)
#size of the box
Lx      = 64.0
Ly      = 64.0
Eext=1.0
Tsim = 300*dt


def initprof1(x,y):
    if (Lx/6.<x<5.*Lx/6.) and (Ly/6.<y<5.*Ly/6.):
        return n0
    else:
        return 0.0

def Profile_Ex(x,y,t):
      return 0.*Eext*sintheta(t, 5.*dt)

def Profile_Ex_ext(x,y):
      return Eext
                
#MAIN()
Main(
    geometry = "2Dcartesian",
    interpolation_order = 4,
    grid_length = [Lx,Ly],
    cell_length = [dx,dy],
    simulation_time = Tsim,
    timestep        = dt,
    number_of_patches = [16,16],
    EM_boundary_conditions = [["silver-muller","silver-muller"],["silver-muller","silver-muller"]], 
    print_every = int(Tsim/dt/100.),
    random_seed = smilei_mpi_rank
)

LoadBalancing(
    initial_balance = True,
    every = 100,
    cell_load = 1.,
    frozen_particle_load = 0.1
)

#ions
Species(
    name      = "ion",
    position_initialization = "random",
    momentum_initialization = "mj",
    particles_per_cell = nppc,
    mass = M,
    charge = Z,
    number_density = initprof1,
    mean_velocity = [0.,0.,0.],
    temperature = [Te],
    boundary_conditions = [["remove","remove"],["remove","remove"]]
)

#electrons
Species(
    name      = "eon",
    position_initialization = "ion",
    momentum_initialization = "mj",
    particles_per_cell = nppc,
    mass = 1.,
    charge = -1.,
    number_density = initprof1,
    mean_velocity = [0.,0.,0.],
    temperature = [Te],
    boundary_conditions = [["remove","remove"],["remove","remove"]]
)


#SETTING EXTERNAL FIELD:
PrescribedField(
    field = "Ex",
    profile = 0.0#Profile_Ex
)


###DIAGNOSTICS
DiagScalar(
    every = 1
)

DiagFields(
    every = 10,
    fields = ["Ex", "Ey", "Bz","Jx","Jy","Rho","Rho_ion","Rho_eon"],
    time_average = 1
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 2,
    time_average = 1,
    species = ["ion"],
    axes = [
        ["x", 0., Lx, 1000],
         ["px", -3, 3, 1000, "edge_inclusive"]
    ]
)

DiagParticleBinning(
    deposited_quantity = "weight",
    every = 2,
    time_average = 1,
    species = ["eon"],
    axes = [
        ["x", 0., Lx, 1000],
         ["px", -3, 3, 1000, "edge_inclusive"]
    ]
)
```

**Comment by mccoys** [comment] 2020-09-16 16:04
Be very careful with PrescribedField. As the doc says, it is not a physical field as it does not follow Maxwell's equations and it is not consistent. If you want to simply do particle trajectories, use test particles.

**Comment by phi-kafka** [comment] 2020-09-16 17:15
Dear mccoys, thank you for your comment. I assume that I know what I am doing, and of course it is not simply do particle trajectories. If you read my post, you can find, that the exponential numerical heating appear in case, when Prescribed Field is set to zero. It means, that there is no Prescribed Field applied. In case there is no Prescribed field, I expect that the setup works as it does without the module named "PrescribedField". However, it is not so. If what I say is correct, it is simply a bug.
Best
ph

**Comment by mccoys** [comment] 2020-09-16 20:04
Ok I apologize for misreading your post. Indeed this should not happen when the field is set to 0. We will investigate ASAP.

**Comment by mccoys** [comment] 2020-09-16 20:05
Ok I apologize for misreading your post. Indeed this should not happen when the field is set to 0. We will investigate ASAP.

**Comment by mccoys** [comment] 2020-09-19 16:12
I found the error will publish the fix soon. Let me close this issue as it turns out to be a duplicate of #281

**Closed by mccoys** 2020-09-19 16:12 UTC
Labels: bug
