### ISSUE TITLE
Checkpoints missing file in 1D simulations

### ISSUE THREAD

**Issue by Kantmq** [SmileiPIC/Smilei#223] opened 2020-03-05 14:16 UTC
Hello everyone

I have an issue on checkpoints for large 1D simulations (I do not have any problem with checkpoints  for even larger simulations in 2D).

## Description

I take too simulations "test_simu_small" and "test_simu_large" which are similar, except by their size which is 16 times larger in  "test_simu_large". See below for the bash, input ,output and error file.

Both simulations run perfectly, and I ask to have a "dump_minutes = 2." and to "exit_after_dump = True".

The code start to dump in both cases (see below output file), but in the case of the larger simulation it does not produce the correct number of dump (the number of dump file should be 64 and the problem is not due to a too large number of dump file since on occigen I can reach much higher number of file per folder).
The time limit asking in the bash file is 06 min for "test_simu_small" and the dump files are created in less than 30 sec. 
For "test_simu_large", the time limit asking in the bash file is 20 min and some dump files are missing, but the dump files present in the checkpoints folder have been created in less than the min. 

Once again, the bash submission and simulations are the same, except that the number of cells is larger in "test_simu_large".
I've tried with a larger number of patches for the larger simulation, and that doesn't change anything.

## Parameters

- I'm using the last version of Smilei 4.3
-I'm running my simulation on OCCIGEN

I don't know if this error is due to a palatalization efficiency.
A similar issue have been observed on an other cluster than OCCIGEN, so I don't think so that the problem come from OCCGEN.

Thanks in advance!

test_simu_small:
[input.txt](https://github.com/SmileiPIC/Smilei/files/4293336/input.txt)
[nqem2d.txt](https://github.com/SmileiPIC/Smilei/files/4293337/nqem2d.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/4293338/out.txt)
[err.txt](https://github.com/SmileiPIC/Smilei/files/4293340/err.txt)

test_simu_large:
[input.txt](https://github.com/SmileiPIC/Smilei/files/4293328/input.txt)
[nqem2d.txt](https://github.com/SmileiPIC/Smilei/files/4293329/nqem2d.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/4293330/out.txt)
[err.txt](https://github.com/SmileiPIC/Smilei/files/4293331/err.txt)

**Comment by mccoys** [comment] 2020-03-05 15:10
could you try ``file_grouping=10`` ?

**Comment by Kantmq** [comment] 2020-03-05 17:09
I've tried before asking since I saw a similar issue in github, but unfortunately it does not change anything.

**Comment by mccoys** [comment] 2020-03-06 08:38
Does is happen every time you try ?

I can see in the error file that the run did not terminate :

```
slurmstepd: error: *** STEP 9793582.0 ON n2622 CANCELLED AT 2020-03-05T15:01:44 DUE TO TIME LIMIT ***
slurmstepd: error: *** JOB 9793582 ON n2622 CANCELLED AT 2020-03-05T15:01:44 DUE TO TIME LIMIT ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
```

This probably means some cores needed more time. It can also mean they are deadlocked.

**Comment by Kantmq** [comment] 2020-03-06 11:43
Yes it happen every time.
Indeed the time limit is reached but I don't think so that it is because some of the cores needed more time. I've ask for 20 min in bash, after 2 min I got 4276 time step (see output),  which mean that the code have 18 min to write the dump file. 
Probably they are deadlocked, but what can I do about that?
Thanks for your answer!

**Comment by mccoys** [comment] 2020-03-06 12:18
I managed to reproduce the bug and will investigate.

**Comment by Kantmq** [comment] 2020-03-06 12:21
Thanks !

**Comment by mccoys** [comment] 2020-03-09 07:41
There seems to be an issue with synchronisation when dump_minutes is used. We are trying to solve the problem, but in the meantime, I recommend using dump_step.

**Comment by mccoys** [comment] 2020-03-13 12:34
@Kantmq This issue should be resolved in the latest commit available on github. Please close the issue if it works for you.

**Comment by Kantmq** [comment] 2020-03-13 13:47
It works for me!
Thanks for your time and your efficiency.
I close the issue.
Best

**Closed** 2020-03-13 13:47 UTC
Labels: bug
