### ISSUE TITLE
installing Smilei on a M1 Macbook using brew

### ISSUE THREAD

**Issue by khpae** [SmileiPIC/Smilei#533] opened 2022-05-12 05:23 UTC
* Need help regarding installation?
   Read this doc first: https://smileipic.github.io/Smilei/installation.html

 * Issues installing C++, MPI, HDF5 or python?
   Please refer to your system administrator first.

 * If you are still in trouble, please provide the result of these commands in the issue:
   git describe --all --long
   make config=verbose
   make env
   echo $LD_LIBRARY_PATH # on mac: echo $DYLD_LIBRARY_PATH
   python -m sysconfig
   ldd smilei

dear, developers and users
I'm trying to install Smilei on a M1 Macbook using brew.
in a terminal, I type

brew install --HEAD iltommi/brews/smilei

to get an warning and fail :
------------------------------
Warning: No available formula with the name "szip" (dependency of iltommi/brews/smilei). Did you mean snzip, sip, zip or ship?
==> Searching for similarly named formulae...
These similarly named formulae were found:
laszip          snzip           sip             zip             ship
To install one of them, run (for example):
  brew install laszip
==> Searching for a previously deleted formula (in the last month)...
szip was deleted from homebrew/core in commit cc40821a6d7:
  szip: remove
  Closes https://github.com/Homebrew/homebrew-core/issues/98261.
  Signed-off-by: Sean Molenaar <1484494+SMillerDev@users.noreply.github.com>
  Signed-off-by: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>

To show the formula before removal, run:
  git -C "$(brew --repo homebrew/core)" show cc40821a6d7^:Formula/szip.rb

If you still use this formula, consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
---------------------------

what should i do to install the code ?
thank you

**Comment by iltommi** [comment] 2022-05-12 06:25
Thanks, this should be fixed now if you do a `brew update && brew reinstall --build-from-source hdf5-parallel`.
It's caused by brew changing a support for used by hdf5, it already was reported by another user a couple of days ago but I forgot to fix it (sorry). In the meanwhile I bumped to the latest hdf5 version.
Feel free to reopen the issue if it does not work

**Closed by iltommi** 2022-05-12 06:25 UTC
Labels: installation

**Comment by khpae** [comment] 2022-05-12 07:08
It worked!
Thank you for the quick and kind reply and troubleshooting.
-- KHP

2022년 5월 12일 (목) 오후 3:25, iltommi ***@***.***>님이 작성:
