### ISSUE TITLE
Happi multiPlot

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#355] opened 2021-01-14 14:13 UTC
Dear Mccoys,

In the last version of SMILEI (happi compiled this morning), I notices several problems with multiPlot / multiSlide :
I try to plot eon/ion densities and px_x for eon/ion thus 4 plots.

When I plot its at several different timesteps it is OK. With animate() it is OK also separately.
With "happi.multiSlide(xe,xp,pxe,pxp,shape=[4,1])" it is OK at t=0 but at later times px_x are empty.

![t0](https://user-images.githubusercontent.com/48507571/104601980-2fed9e80-567b-11eb-9c78-5db572ec774e.png)
![237fs](https://user-images.githubusercontent.com/48507571/104602007-38de7000-567b-11eb-9b03-a387c0fc58c7.png)

And when I try this :
happi.multiPlot(xe,xp,pxe,pxp,shape=[1,4],timesteps=20000) 

I have this error: global name 'timesteps' is not defined

HAve you got an idea?

**Comment by juliencelia** [comment] 2021-01-14 14:17
I use python2.7.17 perhaps I have to use a python 3. version?

**Comment by mccoys** [comment] 2021-01-14 14:37
* Have you checked plotting your px plot alone ? Is it empty as well ?
* I just pushed a fix concerning `timesteps`. This was caused by a recent change.

**Comment by juliencelia** [comment] 2021-01-14 14:41
Alone it is ok. The issue appears with multiPlot or multiSlide.

**Comment by juliencelia** [comment] 2021-01-14 14:49
It seems to concern the 2D plots only

**Comment by juliencelia** [comment] 2021-01-14 14:55
Ok the timesteps kwargs works well now! Thanks

**Comment by mccoys** [comment] 2021-01-14 15:31
Concerning the empty plot, I need more context as it works for me. Do you have an example and basic commands to reproduce the problem ?

**Comment by juliencelia** [comment] 2021-01-14 15:47
I will run a short simulation to try again...
Another point in happi: cbaspect = 0 create an error 
happi.multiPlot(xe,xp,ex,pxe,pxp,shape=[5,1],timesteps=300000)

/ccc/work/cont003/gen6129/bonvalej/Smilei/Smilei_hub/happi/_Utils.pyc in multiPlot(*Diags, **kwargs)
    626                 mp.staticPlot()
    627         else:
--> 628                 mp.animate()
    629 
    630 def multiSlide(*Diags, **kwargs):

/ccc/work/cont003/gen6129/bonvalej/Smilei/Smilei_hub/happi/_Utils.pyc in animate(self)
    558                                 if t in Diag.getTimesteps():
    559                                         if Diag._plot is None:
--> 560                                                 Diag._plotOnAxes(Diag._ax, t, cax_id = Diag._cax_id)
    561                                         else:
    562                                                 Diag._animateOnAxes(Diag._ax, t, cax_id = Diag._cax_id)

/ccc/work/cont003/gen6129/bonvalej/Smilei/Smilei_hub/happi/_Diagnostics/Diagnostic.pyc in _plotOnAxes_2D(self, ax, t, cax_id)
    721                 self._setTitle(ax, t)
    722                 self._setAxesOptions(ax)
--> 723                 self._setColorbarOptions(ax.cax[cax_id].ax)
    724                 return self._plot
    725 

KeyError: 0

**Comment by mccoys** [comment] 2021-01-14 15:51
0 is not an acceptable value for cbaspect

**Comment by juliencelia** [comment] 2021-01-14 15:53
For the empty plot, as example I define this quantities to plot:
xe=S1.ParticleBinning(6,units=['MeV','um','fs'],data_log=False)
xp=S1.ParticleBinning(4,units=['MeV','um','fs'],data_log=True) 
pxp=S1.ParticleBinning(5,units=['MeV/c','um','fs'],data_log=True,cmap=viridis')

When I do : happi.multiSlide(xe,xp,pxp,shape=[3,1]) it is OK at t=0. If I move the cursor, the 2D plot pxp becomes empty...
If I do happi.multiSlide(xe,xp,pxp,shape=[3,1],timesteps=50000) it is OK.

Same thing with multiPlot...

**Comment by juliencelia** [comment] 2021-01-14 15:57
> 0 is not an acceptable value for cbaspect

But It worked several months ago ;)
If you want to hide the colorbar ?

**Comment by mccoys** [comment] 2021-01-14 16:16
This is not possible at the moment in smilei.

If it was possible, it was a bug in matplotlib that was fixed at some point. Maybe you have updated matplotlib recently.

**Comment by juliencelia** [comment] 2021-01-19 11:45
Hi Mccoys,

I tried a light 1d simulation.
Indeed, for the 2D plot (px-x particleBinning) the .animate() method does not work whereas for a 1D plot it is OK...

Here is the results folder  if that can help you:

https://filesender.renater.fr/?s=download&token=bcdcd0c3-1198-49e6-816c-f2ad20dc5d27

Thanks

Julien

**Comment by mccoys** [comment] 2021-01-19 11:57
Could you simply send the simulation input and the commands you use to plot ?

**Comment by juliencelia** [comment] 2021-01-19 12:04
Sure.
[BNH1d_ion.txt](https://github.com/SmileiPIC/Smilei/files/5835686/BNH1d_ion.txt)


S=happi.Open('.')  
S.ParticleBinning(1,units=['MeV','um','fs'],data_log=True,cmap='viridis').plot(timestep=....)    WORKS
S.ParticleBinning(1,units=['MeV','um','fs'],data_log=True,cmap='viridis').animate()    BUG

but S.ParticleBinning(0,units=['um','fs'],data_log=True).animate()  Works fine (1D diag)

**Comment by mccoys** [comment] 2021-01-19 12:06
It says I need a file `hydro.txt` ...

**Comment by juliencelia** [comment] 2021-01-19 12:10
Sorry it is the hydro data file to initialize the plasma densities and temperatures.

[hydro.txt](https://github.com/SmileiPIC/Smilei/files/5835751/hydro.txt)

**Comment by mccoys** [comment] 2021-01-19 12:45
Nevermind. I downloaded your zip file, and it still works for me both on python2 and python3.

What is your version of matplotlib ?

**Comment by juliencelia** [comment] 2021-01-19 12:53
Ouch! It works on my computer. It is on the HPC DRIVE that the issue appears.
I am in python 2.7.17 and matplotlib is the 2.12 version

**Comment by mccoys** [comment] 2021-01-19 12:55
Can you update to 2.2 at least ?

**Comment by juliencelia** [comment] 2021-01-19 12:58
Can I do that by my own or I have to ask to the hotline?

**Comment by mccoys** [comment] 2021-01-19 14:05
you can do both

**Closed** 2021-01-27 13:07 UTC
Labels: bug, happi

**Comment by juliencelia** [comment] 2021-01-29 08:10
Just for information. Hotline does not want to change matplotlib. They call that a "critical" package.
But I just export mine from my computer (2.2.3) on HPCdrive and it works now. 
Thanks a lot mccoys.
