### ISSUE TITLE
Error message in 1Dcartesian

### ISSUE THREAD

**Issue by Z10Frank** [SmileiPIC/Smilei#683] opened 2024-01-02 14:43 UTC
Following is a bug report from @tmiethlinger in the code chat:

"I get the following error in my smilei simulations:
```
 [ERROR](0) src/PartCompTime/PartCompTimeFactory.h:73 (create)
 A probem was found in the namelist:
 > Unknwon parameters setting the particle computing time evaluation operator: 1Dcartesian, Order : 4
```
if I include particle collisions (any pair of species) to my 1Dcartesian, 4th-order particle shape simulations.
It works with 2nd-order particles, or 4th-order particles without collisions."

**Comment by mccoys** [comment] 2024-01-18 11:22
@tmiethlinger Please do not use adaptive vectorization in 1D. It is not available yet.

**Comment by mccoys** [comment] 2024-01-18 11:22
This is in fact a duplicate of #428

**Closed by mccoys** 2024-01-18 11:22 UTC
Labels: duplicate, feature-request
