### ISSUE TITLE
Build fails when hdf5 isn't built with the PARALLEL option

### ISSUE THREAD

**Issue by yurivict** [SmileiPIC/Smilei#650] opened 2023-08-28 03:17 UTC
## Description
```
In file included from src/Checkpoint/Checkpoint.cpp:7:
In file included from src/Checkpoint/Checkpoint.h:16:
src/Tools/H5.h:352:17: error: use of undeclared identifier 'H5Pget_dxpl_mpio'
                H5Pget_dxpl_mpio( dxpl_, &xfer );
                ^
src/Tools/H5.h:353:17: error: use of undeclared identifier 'H5Pset_dxpl_mpio'
                H5Pset_dxpl_mpio( dxpl_, H5FD_MPIO_INDEPENDENT );
                ^
src/Tools/H5.h:355:17: error: use of undeclared identifier 'H5Pset_dxpl_mpio'
                H5Pset_dxpl_mpio( dxpl_, xfer );
                ^
src/Tools/H5.h:370:17: error: use of undeclared identifier 'H5Pget_dxpl_mpio'
                H5Pget_dxpl_mpio( dxpl_, &xfer );
                ^
src/Tools/H5.h:371:17: error: use of undeclared identifier 'H5Pset_dxpl_mpio'
                H5Pset_dxpl_mpio( dxpl_, H5FD_MPIO_INDEPENDENT );
                ^
src/Tools/H5.h:373:17: error: use of undeclared identifier 'H5Pset_dxpl_mpio'
                H5Pset_dxpl_mpio( dxpl_, xfer );
                ^
```

This is because ```H5Pset_dxpl_mpio``` is only defined when hdf5 is built with the PARALLEL option.

Unfortunately, the PARALLEL option seems to be brokn in hdf5, because it isn't compatible with some other options that we in general need: https://github.com/HDFGroup/hdf5/issues/3235

Is there a way to build Smilei w/out hdf5 having the PARALLEL option?

## Parameters

- Smilei version ? 4.7-1037-g81d858dd9
- Computing resources
  - type of computer: desktop
  - OS: FreeBSD 13.2
  - C++ compiler (to get some information `g++ --version`): clang-16
  - MPI version (`mpic++ --version`, `mpic++ -show`): n/a
  - HDF5 version (`h5cc --version`): hdf5-1.12.2
  - Python version (`python --version`): 3.9

**Comment by iltommi** [comment] 2023-08-28 06:18
Unfortunately, Smilei is an HPC and need these options to perform on supercomputers. 
Most package manager provide both libraries in separate packages. On Ubuntu for example there are both mpich and openmpi linked hdf5 libs.
(You might wonder why hdf5group does not separate them, but that's out of reach for me...)

**Comment by yurivict** [comment] 2023-08-28 06:24
Hopefully they will fix hdf5 so that Smilei can be compiled on FreeBSD as well.

**Comment by iltommi** [comment] 2023-09-20 07:35
We're closing this for now, feel free to reopen if you think we can do something on our side.
Thanks for reporting

**Closed by iltommi** 2023-09-20 07:35 UTC
Labels: installation

**Comment by CarloCobal** [comment] 2025-04-21 17:54
Any updates on this? Trying to run on my home Mac

**Comment by mccoys** [comment] 2025-04-21 21:52
There are no updates as this is not a bug. It is necessary to have a parallel hdf5 version. 

For Mac, have you tried the brew recipe? I'm not sure how recently it has been updated
https://smileipic.github.io/Smilei/Use/install_macos.html

**Comment by iltommi** [comment] 2025-04-22 11:53
Sorry there is indeed a problem with the installation for macos (which is very old).

In principle these commands should be enough to get smilei compiled on a macos:

You need to install brew first (look here: https://brew.sh/) then:
```
brew install python numpy hdf5-mpi
```

Export these variables (you may want to put them in your `~/.zshrc` or similar)
```
export PYTHONEXE=python3
export OMPI_CXX=g++-14
export HDF5_ROOT_DIR=$(brew --prefix hdf5-mpi)
```

Finally you should be able to compile with just the command `make` in the Smilei folder
