### ISSUE TITLE
Problem running simulations with high-Z ions

### ISSUE THREAD

**Issue by humanoid-v1911** [SmileiPIC/Smilei#284] opened 2020-08-21 12:38 UTC
I have done some simulations for a laser impacting a hydrogen plasma and wanted to do the same set of simulations for a high-Z plasma (carbon ions). For this I used my previously working namelist and made some changes to the ion species block (increase in charg from 1 to 6 & increase in mass from 1836 for protons to a bit more then it's 6-fold).

The simulations seem to initialize properly as expected but then abort quickly after just a couple, if any, timesteps. 

Right now I am clueless as to what gives this error since I've tried running it on different queues on the cluster used and at different times. So a single isolated cluster-sided-error can't be it. 

I've attached the namelist as well as the stderr output

**Abortion message from stdout-file:**
`mpirun noticed that process rank 224 with PID 11678 on node lfc147.mpi-hd.mpg.de exited on signal 6 (Aborted).`

**stderr-file output:**

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Stack trace (most recent call last):
#15   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#14   Object "/home/theo/XXX/happi_virtualenv/smilei", at 0x47baf3, in 
#13   Object "/lib64/libc.so.6", at 0x2af19f710544, in __libc_start_main
#12   Object "/home/theo/XXX/happi_virtualenv/smilei", at 0x4700a3, in main
#11   Object "/usr/local/Packages/gcc-6.1.0/lib64/libgomp.so.1", at 0x2af19f2b8e2e, in GOMP_parallel
#10   Object "/home/theo/XXX/happi_virtualenv/smilei", at 0x6d333f, in 
#9    Object "/home/theo/XXX/happi_virtualenv/smilei", at 0x658839, in VectorPatch::dynamics(Params&, SmileiMPI*, SimWindow*, RadiationTables&, MultiphotonBreitWheelerTables&, double, Timers&, int)
#8    Object "/home/theo/XXX/happi_virtualenv/smilei", at 0x6f36e6, in Species::dynamics(double, unsigned int, ElectroMagn*, Params&, bool, PartWalls*, Patch*, SmileiMPI*, RadiationTables&, MultiphotonBreitWheelerTables&, std::vector<Diagnostic*, std::allocator<Diagnostic*> >&)
#7    Object "/usr/local/Packages/gcc-6.1.0/lib64/libgcc_s.so.1", at 0x2af19f4e8486, in _Unwind_Resume
#6    Object "/usr/local/Packages/gcc-6.1.0/lib64/libgcc_s.so.1", at 0x2af19f4e7f82, in 
#5    Object "/usr/local/Packages/gcc-6.1.0/lib64/libstdc++.so.6", at 0x2af19efa40dc, in __gxx_personality_v0
#4    Object "/usr/local/Packages/gcc-6.1.0/lib64/libstdc++.so.6", at 0x2af19efa3718, in 
#3    Object "/usr/local/Packages/gcc-6.1.0/lib64/libstdc++.so.6", at 0x2af19efa4755, in 
#2    Object "/usr/local/Packages/gcc-6.1.0/lib64/libstdc++.so.6", at 0x2af19efa67ac, in __gnu_cxx::__verbose_terminate_handler()
#1    Object "/lib64/libc.so.6", at 0x2af19f725a67, in abort
#0    Object "/lib64/libc.so.6", at 0x2af19f724377, in gsignal
Aborted (Signal sent by tkill() 11678 6948)
```

**Namelist**

[LaserChannel.txt](https://github.com/SmileiPIC/Smilei/files/5108826/LaserChannel.txt)

**Comment by mccoys** [comment] 2020-08-24 08:50
Actually, the `bad_alloc` error probably means you are out of memory. You may need to allocate more nodes for that run. Maybe because too many particles are created ?

**Comment by humanoid-v1911** [comment] 2020-08-24 14:40
I'm running on 256 cores in parallel with openmpi, if this is what you're asking for? It's the same setup I was using before for the hydrogen plasma.

The number of particle per cells was reduced from 16 to 4 for ions compared to working simulations before. Further reduction seems not to be possible for the ion species since the number of particles per cell needs to be a square number or I would need to use a random distribution. 
Maybe the increase in mass causes this? 

For further information I'll have to check my job submission file.

**Comment by mccoys** [comment] 2020-08-25 12:08
Do you use openMP parallelism ? Or only MPI ?

I don't think the change in mass should be the problem, but until I can reproduce the bug, it is hard to tell.

**Comment by humanoid-v1911** [comment] 2020-08-25 22:47
I'm using openMP. 

Would the job-submission file be of use to you?

**Comment by mccoys** [comment] 2020-08-26 06:58
I just need to know the number of openmp threads in each MPI. The submission file would help. The full log as well if you have it.

**Comment by humanoid-v1911** [comment] 2020-08-27 23:44
Here are the submission file and the stdout file, I hope this helps.


[stdout.txt](https://github.com/SmileiPIC/Smilei/files/5139189/stdout.txt)
[job_smilei_openmpi.txt](https://github.com/SmileiPIC/Smilei/files/5139191/job_smilei_openmpi.txt)

**Comment by mccoys** [comment] 2020-09-07 08:00
You are using the original v4.5. Many changes have been brought to the current version in the repository although they have not been released in 4.6 yet. Could you try the lastest commit available ?

**Comment by humanoid-v1911** [comment] 2020-09-15 16:03
I've made a fresh install with the latest version of smilei but ran into the same error again. 

I now have set for the ion species a charge of 6, the particles per cell back to it's original value of 16 and created a new density profile for the ion species which adjusts for the ratio of ions/electron of 1/6 but is otherwise the same as before. Up until yet it seems to run properly, however I have not yet adjusted the particles mass. I'll keep you updated if this work-around works.

**Comment by humanoid-v1911** [comment] 2020-10-06 23:37
It seems the problem for the simulations not running properly was the number of particles per cell of the ions being different than the other particles'. I've set it on the old value and added a second density function which let me set the ration of electrons/ions to 6 as intended.

**Comment by mccoys** [comment] 2020-10-07 07:34
I do not think this is the direct reason. But it can indirectly modify the memory footprint.

**Comment by mccoys** [comment] 2020-10-07 10:15
Actually I reproduced your simulation. It greatly slows down from timestep 1500 or so. Probably because you create many particles which saturate the memory. Hence the error.

**Comment by mccoys** [comment] 2020-10-07 11:30
Here is your number of photons
![image](https://user-images.githubusercontent.com/4188478/95325246-33fe6900-08a1-11eb-876b-971e546360db.png)

**Comment by mccoys** [comment] 2020-10-07 11:31
I am closing this because it is not a bug.

**Closed by mccoys** 2020-10-07 11:31 UTC
Labels: bug
