### ISSUE TITLE
Incorrect particle number when loading particles from numpy array

### ISSUE THREAD

**Issue by HaoPengYY** [SmileiPIC/Smilei#562] opened 2022-09-07 08:00 UTC
Dear Developers,

Hi. I am using SMILEI3D to simulate an electron bunch colliding with an intense laser and save their trajectories. Since I need to customize the electron bunch (like its distribution, energy, et al.)  I create numpy arrays and initialize the electron bunch as described in [the documentation of SMILEI](https://smileipic.github.io/Smilei/namelist.html#:~:text=A%20numpy%20array%20or%20an%20HDF5%20file%20defining%20all%20the%20positions%20of%20the%20particles.%20In%20this%20case%20you%20must%20also%20provide%20the%20weight%20of%20each%20particle%20(see%20Macro%2Dparticle%20weights).%20See%20Initialize%20particles%20from%20an%20array%20or%20a%20file.), which always works quite well. The problem is the number of the initialized particles in this way usually does match the number I set.

For example, in the input script attached, I intended to initialize 10 electrons with different initial positions. But actually, when I run the simulation and try to extract the trajectories, I only get 8.  I have tried with more particles, like 10000 or 50000, sometimes I got a little bit more, sometimes I got a little bit less. The actual number is close but randomly floating around the number I set in the input script. So, is there a way to make the actual number stable?  When I got more particles than I expected, what are their initial positions like?  Thanks a lot in advance.
[input.txt](https://github.com/SmileiPIC/Smilei/files/9503931/input.txt)

**Comment by beck-llr** [comment] 2022-09-07 08:26
Hi
Thanks for the feedback. Are you absolutely sure that all the `(x,y,z)` coordinates you provide are within the boundaries of your simulation ?
What if you try a dummy simulation with 10 electrons at the same position ? Do you still get only 8 ?

**Comment by HaoPengYY** [comment] 2022-09-08 02:46
@beck-llr Thanks for you quick reply. Yes, the particles initialized are all inside the simulation box, as you can find in the input script attached. Actually, I have been doing this for like almost one year with SMILEI. I dump the electron trajectories to calculate their far-field radiation, results are right and agree well with theory. I usually use tens of thousands of electrons, but every time the actual electron number just differed from the number I set by several tens, which seems weird. I suppose it is because electrons are created by different MPIs, some of them are created repeatedly, while some of them are lost.

**Comment by beck-llr** [comment] 2022-09-08 06:09
Yes you are correct. Each MPI process goes through the list of particles and create the ones which belong to its domain. But that does not explain why certain electrons would not be created initially.
Another possibility is that some of the particles get out of the domain and are removed by the boundary condition before you start tracking them at `t = t_trace_start`.

**Comment by mccoys** [comment] 2022-09-08 06:54
One possibility is that a few particles being precisely at patch boundaries are not taken into any patch by error.

**Comment by beck-llr** [comment] 2022-09-08 08:23
What surprises me is that it can occur with as few as 10 particles.

**Comment by HaoPengYY** [comment] 2022-09-08 09:16
No

> Yes you are correct. Each MPI process goes through the list of particles and create the ones which belong to its domain. But that does not explain why certain electrons would not be created initially. Another possibility is that some of the particles get out of the simulation domain and are removed by the boundary condition before you start tracking them at `t = t_trace_start`.

In my simulations, the particles are propagating away from the boundaries. I believe they are still inside the simulation box when I start the tracking. After all, this cannot explain the fact sometimes I got more particles than I put inside the box. 


> What surprises me is that it can occur with as few as 10 particles.

Yes, this succeeds even when I use 480 MPI processors.

**Comment by beck-llr** [comment] 2022-09-08 10:00
The output log should tell you exactly how many particles are created by species. Is this number correct and differ from the number of particles you get in the `TrackParticles` diagnostic ?

**Comment by HaoPengYY** [comment] 2022-09-09 00:23
The output log of the simulation on the input script I attached told me 8 particles are created, same as the number of particles I get in the` TrackParticles`. Shown below is one of examples I got more particles in the output and `TrackParticles`.
![image](https://user-images.githubusercontent.com/81665726/189247578-3cdfcaf0-de9f-4276-85ff-11208bc4b5ca.png)
![image](https://user-images.githubusercontent.com/81665726/189247634-27d99793-f952-4e3c-be46-1372d42e1d34.png)

**Comment by mccoys** [comment] 2022-09-09 08:25
I am able to reproduce the error. It comes from the python object being garbage collected to early, and some data is lost or replaced. Working on it.

**Comment by HaoPengYY** [comment] 2022-09-09 08:43
> I am able to reproduce the error. It comes from the python object being garbage collected to early, and some data is lost or replaced. Working on it.

Nice! Thanks a lot.

**Comment by mccoys** [comment] 2022-09-09 09:24
Sorry I was wrong in my analysis. The issue is not in the garbage collection. The problem is in your namelist.

You generate random number but every MPI process will generate them independently so that they do not have the same particles. You have to make sure all processes have exactly the same numbers.

(By the way you should not use random_seed = smilei_mpi_rank)

**Comment by HaoPengYY** [comment] 2022-09-09 09:35
Hi. Do you mean that every MPI read the input script and executes the function to create the particles indecently? I didn't know that. So maybe I should write a separate script to initialize these particles and save them as hdf5 file, then I import them in the input script, right? Or can I specify the rank in the input script like using `if rank==0`, then create the particles?

Actually, I don't what does ` random_seed=smilei_mpi_rank` means, I just copy input scripts from the benchmark directory and make changes to have my own input script. So, if I initialize a species and I want the microscopic distribution to be random, how do I do that, please?

**Comment by beck-llr** [comment] 2022-09-09 09:48
> Do you mean that every MPI read the input script and executes the function to create the particles indecently?

Yes this is how it works. Each MPI computes the list of particles instead of computing it on a local process and broadcast it.

> So maybe I should write a separate script to initialize these particles and save them as hdf5 file, then I import them in the input script

This is one possible option.

> Or can I specify the rank in the input script like using if rank==0, then create the particles ?

You could do that but then only rank 0 would create particles and that is not what you want.

>  I don't what does random_seed=smilei_mpi_rank means

This means every MPI rank has a different random seed. The random number generator will therefore generate different sets of numbers for each MPI. This is convenient for instance if you want random pattern of particle positions to be different from one MPI to another. But in your case it leads to different lists of particles to generate.
If you set `random_seed = 0` for instance (or any constant), all MPI should generate the same set of random numbers and therefore the same list of particles in your case.

**Comment by mccoys** [comment] 2022-09-09 10:15
WARNINGS

* do not use hdf5 file input right now. There is a bug that will be fixed very soon. When it is fixed, this will be the best option.
* `random_seed = 0` is a good thing to do in any case. **But it will not work for your particular situation**. The reason is that the random seed for Smilei is not the same seed as the seed for python. As you are generating random numbers directly in the python script, you must handle the random seed from your python script directly. I can see that you use two different random number generators (`truncnorm` from scipy, and `random` from numpy). You must set a fixed seed for both.

Another way to handle this situation would be to use mpi4py if you know how to use it. You can make the first rank make the arrays, then communicate them to all MPIs.

**Comment by HaoPengYY** [comment] 2022-09-11 01:21
@mccoys Thanks a lot. I do know mpi4py, but how do I do it, please? Like, in the input script, I import mpi4py, initialize MPI, then if rank==0, let the master create the array then broadcast. In the species block, just let `position_initialization=array_broadcasted`? (Or I can just let the master broadcast a single numpy random seed? )

Another possible option is the 'quasi-random' loading method used in [the simulation of free electron laser](http://genesis.web.psi.ch/download/documentation/genesis_thesis.pdf), it is more complex,  qseudo-random thus controllable and using this method the particle distribution is close to realistic.

**Comment by mccoys** [comment] 2022-09-11 06:10
Broadcasting the seed or broadcasting the array are both good methods

**Comment by HaoPengYY** [comment] 2022-09-13 00:08
@mccoys Thanks, I will try. Thanks a lot. I will paste the results here. This issue is now OK to close.

**Closed** 2022-09-13 06:46 UTC
Labels: how-to
