### ISSUE TITLE
Segmentation faults

### ISSUE THREAD

**Issue by Tissot11** [SmileiPIC/Smilei#402] opened 2021-05-09 12:05 UTC
I'm having weird issue. I tried to compile Smilei (Git, v4.6,v4.5). Compilations proceed fine without any errors or warnings with different mpi (opnempi 4.0.2 and intel), compilers (gcc, mpiicpc) and  different hdf5. However, on running simulations, I'm encountering segmentation faults with messages like below

` PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../../../../opal/mca/pmix/pmix3x/pmix/src/mca/bfrops/v12/unpack.c at line 206`

`PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../../../../opal/mca/pmix/pmix3x/pmix/src/mca/bfrops/v12/unpack.c at line 147`

`Stack trace (most recent call last) in thread 55439:
#9    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#8    Object "/lib64/libc.so.6", at 0x2b0347f9a2dc, in clone
#7    Object "/lib64/libpthread.so.0", at 0x2b03457626d9, in 
#6    Object "/mpcdf/soft/SLE_12/packages/x86_64/intel_parallel_studio/2018.4/18.0/linux/compiler/lib/intel64/libiomp5.so", at 0x2b034799aeb0, in 
#5    Object "/mpcdf/soft/SLE_12/packages/x86_64/intel_parallel_studio/2018.4/18.0/linux/compiler/lib/intel64/libiomp5.so", at 0x2b034795d23a, in 
#4    Object "/mpcdf/soft/SLE_12/packages/x86_64/intel_parallel_studio/2018.4/18.0/linux/compiler/lib/intel64/libiomp5.so", at 0x2b034795dcd9, in 
#3    Object "/mpcdf/soft/SLE_12/packages/x86_64/intel_parallel_studio/2018.4/18.0/linux/compiler/lib/intel64/libiomp5.so", at 0x2b034799aa42, in __kmp_invoke_microtask
#2    Object "/u/nkumar/CodeRepositeDraco/Smilei-v4.6/./smilei", at 0xade7de, in main
#1    Object "/u/nkumar/CodeRepositeDraco/Smilei-v4.6/./smilei", at 0x9e25a4, in VectorPatch::injectParticlesFromBoundaries(Params&, Timers&, unsigned int)
#0    Object "/u/nkumar/CodeRepositeDraco/Smilei-v4.6/./smilei", at 0x907b2f, in ParticleCreator::create(SubSpace, Params&, Patch*, unsigned int)
Segmentation fault (Address not mapped to object [0x802036c58])
srun: error: dra0756: task 0: Segmentation fault
srun: Terminating job step 20397821.0
slurmstepd: error: *** STEP 20397821.0 ON dra0756 CANCELLED AT 2021-05-09T09:35:25 ***
srun: error: dra0756: tasks 1-7: Terminated
srun: error: dra0757: tasks 9-15: Terminated
srun: error: dra0758: tasks 16-23: Terminated
srun: error: dra0759: tasks 24-31: Terminated
srun: error: dra0757: task 8: Terminated
srun: Force Terminated job step 20397821.0`

I have tried this on different machines with different Namelists and it is similar everywhere. But my compiled code from last year (v4.4 fetched from GitHub) is working absolutely fine. Any suggestions, what might be wrong or what to try?

**Comment by mccoys** [comment] 2021-05-09 18:39
Does it happen with the benchmarks given in the source code? Or with specific cases?

**Comment by Tissot11** [comment] 2021-05-09 18:56
I tried two of my Namelists, that work fine with the older version (v4.4) on different machines. I didn't try with the benchmarks. I'm not sure where the problem is.

**Comment by mccoys** [comment] 2021-05-10 07:50
Can you try a few benchmarks ?

**Comment by xxirii** [comment] 2021-05-10 08:00
Hi @Tissot11, can you send us a small namelist that produce the error ? If possible the smallest and running on a single proc.

**Comment by Tissot11** [comment] 2021-05-10 10:08
@mccoys , I have not tried the benchmarks yet but I could manage to run another Namelist of mine successfully. Then the issue appears to be with one of the Namelist.

@xxirii I attach the a short version of this Namelist here. It runs fine with v4.4(fetched from gitHub) but crashes with 4.5 and 4.6 (both tarball and GitHub releases). This crash is irrespective of compilers, mpi, and hdf5. You can run it on 1 proc since the crash happens right after setting up the patches etc.

[crashedNamelist.txt](https://github.com/SmileiPIC/Smilei/files/6451247/crashedNamelist.txt)

**Comment by xxirii** [comment] 2021-05-11 07:40
I confirm I can reproduce the bug on my local computer. I will let you know when I have a solution, probably not before next week.

**Comment by Tissot11** [comment] 2021-05-11 08:20
Thanks for looking into this. Please let me know when you have a solution.

**Comment by xxirii** [comment] 2021-05-18 09:56
Dear @Tissot11 ,

I have found the cause of the bug. I made a correction that will be integrated in the master version when it passes all check tests.

The cause of the bug was an incompatibility between the injector and the classical particle creation when initializing particles at the position of another species. Smilei uses a class called `ParticleCreator` to generate a vector of particles. This class is used both for the creation of the domain particles at t=0 and by injectors. A sanity check has been implemented for the particle creation leading as well to an incompatibility with the injection is specific configurations.

**Comment by Tissot11** [comment] 2021-05-18 11:28
Dear @xxirii, many thanks for the fast fixing of the bug!

**Comment by xxirii** [comment] 2021-05-19 07:12
The correction is pushed to the master branch of the GitHub. I will close this issue only if you confirm that it is working correctly for you.

**Comment by Tissot11** [comment] 2021-05-20 14:28
Thanks for the fix. I have checked it on one machine and Smilei is running fine. So the latest push appears to have solved the problem.

**Closed** 2021-05-20 15:51 UTC
Labels: bug
