### ISSUE TITLE
MPI issue on CELIA cluster

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#373] opened 2021-03-03 15:36 UTC
Dear SMILEI team,

Hope you are well.
We have just installed SMILEI on our new cluster at the CELIA.
Smilei runs well in pure openMP mode. With more than one MPI process, we have a problem of MPI tag number...

Abort(738829828) on node 1 (rank 1 in comm 0): Fatal error in PMPI_Iprobe: Invalid tag, error stack:
PMPI_Iprobe(119): MPI_Iprobe(src=0, tag=16777216, MPI_COMM_WORLD, flag=0x7ffdcb47acec, status=0x7ffdcb47aed8) failed
PMPI_Iprobe(91).: Invalid tag, value is 16777216

The modules loaded are:

module load smilei/
module load zlib/1.2.11
module load intel-2020/2020
module load intel-mpi/mpi
module load hdf5-1.12-int
module load python2/
module load hdf5-1.12-intelmpi/hdf5-intelmpi

the simulation has only 32*4 patches. The simulation is launched with 2MPI*16openMP.

The export are:
export OMP_NUM_THREADS=16
export OMP_SCHEDULE=dynamic
export OMP_PROC_BIND=TRUE

Have you got an idea?
Thanks

Julien

**Comment by mccoys** [comment] 2021-03-03 15:45
Duplicate of #270 #307 
* update smilei
* set variables:
```
$ export MPIR_CVAR_CH4_OFI_TAG_BITS=25
$ export MPIR_CVAR_CH4_OFI_RANK_BITS=14
```

**Comment by juliencelia** [comment] 2021-03-08 12:00
Thanks. Smilei works perfectly on our new cluster!

**Closed** 2021-03-08 12:12 UTC
Labels: duplicate
