### ISSUE TITLE
particle remove in 3D

### ISSUE THREAD

**Issue by phi-kafka** [SmileiPIC/Smilei#305] opened 2020-09-27 20:19 UTC
Dear Smiliers,
I simulate plasma flow propagation in 3D, which comes from x=0 with particle injector. I notice that when flow comes to the opposite side, after some time it starts to reflect, while the boundary conditions are set to "remove" everywhere. What is wrong?
Here is the illustration: 
[present.pdf](https://github.com/SmileiPIC/Smilei/files/5289009/present.pdf)
 I use Version : v4.4-783-g9183dad-master
Thanks

**Comment by xxirii** [comment] 2020-09-28 08:20
Dear @phi-kafka,

Your issue is similar to #293. We need to work on this to understand what is happening. Can you confirm that the problem does not arises when injection is off?

**Comment by mccoys** [comment] 2020-09-28 09:10
@phi-kafka Is it possible to have an input file that reproduces the error ?
Are you using a moving window ?

**Comment by phi-kafka** [comment] 2020-09-28 09:30
> Dear @phi-kafka,
> 
> Your issue is similar to #293. We need to work on this to understand what is happening. Can you confirm that the problem does not arises when injection is off?

No, it seems that the problem is still there. I will make the example.

> @phi-kafka Is it possible to have an input file that reproduces the error ?
> Are you using a moving window ?
Yes, I will prepare input files. No, I don't use moving window.

**Comment by mccoys** [comment] 2020-09-29 09:41
I am closing this as a duplicate of #293.
Please read my last comment on that other issue.

**Closed by mccoys** 2020-09-29 09:41 UTC
Labels: duplicate
