### ISSUE TITLE
Time to record dump files

### ISSUE THREAD

**Issue by juliencelia** [SmileiPIC/Smilei#228] opened 2020-03-20 09:47 UTC
I have the last version of SMILEI (from Github) installed 2 days ago on KNL.
I lost millions of CPU hours for nothing since weeks :(

I have always a problem with checkpoints. I attach files of simulation.
I tested this simualtion with dump at 2000 timesteps. It works very well : in checkpoints/ folder I have 7 folders (0 to 6) with the 200 files corresponding to 200 MPI process.

When I want to launch the real simulation with dump_minutes at 1360min (81600s) for a reservation on KNL job submission of 86000s, the checkpoints/ folder contains 7 folders but only the 1/and 0/ forlder contains something. Others are empty.

So in 1h and 15min, SMILEI couldn't record 1/5 of the dump files? Or is it another issue that I can't see?

[BNH2d.txt](https://github.com/SmileiPIC/Smilei/files/4358792/BNH2d.txt)
[out.txt](https://github.com/SmileiPIC/Smilei/files/4358796/out.txt)
[job_sub.txt](https://github.com/SmileiPIC/Smilei/files/4358803/job_sub.txt)

**Comment by beck-llr** [comment] 2020-03-20 09:56
Hi
This is most likely related to a problem with the `dump_minute` feature which seems to fall into deadlocks these days. I'm afraid you will have to use `dump_step` in your production run too. A fix to that issue was proposed recently but either it doesn't work for you or you haven't used it. Can you run a `git log` and tell us the latest commit you have in your smilei directory please ?

**Comment by juliencelia** [comment] 2020-03-20 12:44
I download zip 2 days ago from Github. As I said you in Bordeaux, I don't use Git with TGCC.

**Comment by beck-llr** [comment] 2020-03-20 12:49
You could `git clone` to your personal computer and then copy everything manually to TGCC.

**Comment by juliencelia** [comment] 2020-03-20 12:50
I try with dump_step at the step that corresponds to dump_minute. I'll see if the problem come from dump_minute feature. 

Yes for git cloning, I will do that from now. It could be easier for exchange about issues or other with the team.

Thanks Arnaud

**Comment by mccoys** [comment] 2020-03-20 13:34
Duplicate of #223

**Comment by juliencelia** [comment] 2020-03-21 14:32
Actually it works well with dump_step!
I never had that at the end of the log file:

 End time loop, time dual = 6646.602
 --------------------------------------------------------------------------------


 Time profiling : (print time > 0.001%)
 --------------------------------------------------------------------------------
 Time in time loop :    77898.063       98.163% coverage
                   Particles    34986.289       44.913%
                     Maxwell    26.389  <1%
                 Diagnostics    13775.489       17.684%
                  Collisions    3.068   <1%
              Load balancing    1419.458        1.822%
              Sync Particles    20127.500       25.838%
                 Sync Fields    155.723 <1%
              Sync Densities    7320.777        9.398%
                Part Merging    2.474   <1%
              Part Injection    8.989   <1%

         Printed times are averaged per MPI process
                 See advanced metrics in profil.txt

        Diagnostics profile :
                         scalars.txt    261.210
                 ParticleBinning0.h5    113.180
                 ParticleBinning1.h5    444.371
                 ParticleBinning2.h5    240.122
                 ParticleBinning3.h5    235.385
                 ParticleBinning4.h5    116.936
                 ParticleBinning5.h5    234.530
                 ParticleBinning6.h5    244.979
                 ParticleBinning7.h5    235.241
                 ParticleBinning8.h5    2.330
                 ParticleBinning9.h5    191.370
                ParticleBinning10.h5    225.337
                ParticleBinning11.h5    208.119
                ParticleBinning12.h5    248.518
                ParticleBinning13.h5    275.745
                          Probes0.h5    7747.848
                TrackParticlesDisordered_iZ5.h5 951.496
                TrackParticlesDisordered_iZ7.h5 1290.046
                TrackParticlesDisordered_pon.h5 501.619


 END
But it's not always easy to evaluate at ech timestep simulation could be at the end of a run....

**Comment by mccoys** [comment] 2020-03-21 16:24
As indicated before, we have made a fix that should be available soon.

**Comment by juliencelia** [comment] 2020-03-21 17:51
I know your efficiency @mccoys ans all the team! Thanks again ;)

**Comment by mccoys** [comment] 2020-03-23 12:57
Actually, I forgot that the fix was already available !
Are you sure you have tried with the last version on github ? Did you compile again ?

**Closed** 2020-04-02 18:30 UTC
Labels: duplicate, needs-user-input

**Comment by juliencelia** [comment] 2020-04-02 19:30
It works perfectly with dump_minutes. THANKS!!!
